### ISSUE TITLE
Unity Plugin not working.

### ISSUE THREAD

**Issue by rosank** [mopub/mopub-unity-android-plugin#5]
I followed all the steps, but when i run test scene, application crash, 
Log:
02-12 12:21:13.572: W/MoPub(9129): AndroidManifest permissions for the following required MoPub activities are missing:
02-12 12:21:13.572: W/MoPub(9129): 	com.mopub.mobileads.MraidVideoPlayerActivity
02-12 12:21:13.572: W/MoPub(9129): 	com.mopub.common.MoPubBrowser
02-12 12:21:13.572: W/com.mopub(9129): AndroidManifest permissions for the following required MoPub activities are missing:
02-12 12:21:13.572: W/com.mopub(9129): 	com.mopub.mobileads.MraidVideoPlayerActivity
02-12 12:21:13.572: W/com.mopub(9129): 	com.mopub.common.MoPubBrowser
02-12 12:21:13.602: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest$Listener;' failed
02-12 12:21:13.602: W/dalvikvm(9129): Link of class 'Lcom/mopub/mobileads/AdViewController$1;' failed
02-12 12:21:13.602: E/dalvikvm(9129): Could not find class 'com.mopub.mobileads.AdViewController$1', referenced from method com.mopub.mobileads.AdViewController.<init>
02-12 12:21:13.612: W/dalvikvm(9129): VFY: unable to resolve new-instance 691 (Lcom/mopub/mobileads/AdViewController$1;) in Lcom/mopub/mobileads/AdViewController;
02-12 12:21:13.612: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.612: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.622: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.622: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.622: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.622: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.622: W/dalvikvm(9129): VFY: unable to resolve virtual method 6740: Lcom/mopub/network/AdRequest;.cancel ()V
02-12 12:21:13.632: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.632: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.632: E/dalvikvm(9129): Could not find class 'com.mopub.network.AdRequest', referenced from method com.mopub.mobileads.AdViewController.fetchAd
02-12 12:21:13.632: W/dalvikvm(9129): VFY: unable to resolve new-instance 961 (Lcom/mopub/network/AdRequest;) in Lcom/mopub/mobileads/AdViewController;
02-12 12:21:13.632: W/dalvikvm(9129): VFY: unable to find class referenced in signature (Lcom/mopub/volley/VolleyError;)
02-12 12:21:13.632: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/MoPubNetworkError; (988)
02-12 12:21:13.632: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/MoPubNetworkError;' failed
02-12 12:21:13.642: E/dalvikvm(9129): Could not find class 'com.mopub.network.MoPubNetworkError', referenced from method com.mopub.mobileads.AdViewController.onAdLoadError
02-12 12:21:13.642: W/dalvikvm(9129): VFY: unable to resolve instanceof 967 (Lcom/mopub/network/MoPubNetworkError;) in Lcom/mopub/mobileads/AdViewController;
02-12 12:21:13.642: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/TrackingRequest; (982)
02-12 12:21:13.642: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/TrackingRequest;' failed
02-12 12:21:13.642: W/dalvikvm(9129): VFY: unable to resolve static method 6863: Lcom/mopub/network/TrackingRequest;.makeTrackingHttpRequest (Ljava/lang/String;Landroid/content/Context;Lcom/mopub/common/event/MoPubEvents$Type;)V
02-12 12:21:13.642: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.642: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.652: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.652: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.652: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.652: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.652: W/dalvikvm(9129): VFY: unable to resolve virtual method 6744: Lcom/mopub/network/AdRequest;.isCanceled ()Z
02-12 12:21:13.652: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/TrackingRequest; (982)
02-12 12:21:13.652: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/TrackingRequest;' failed
02-12 12:21:13.652: W/dalvikvm(9129): VFY: unable to resolve static method 6863: Lcom/mopub/network/TrackingRequest;.makeTrackingHttpRequest (Ljava/lang/String;Landroid/content/Context;Lcom/mopub/common/event/MoPubEvents$Type;)V
02-12 12:21:13.662: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest$Listener;' failed
02-12 12:21:13.662: W/dalvikvm(9129): Link of class 'Lcom/mopub/mobileads/AdViewController$1;' failed
02-12 12:21:13.662: W/dalvikvm(9129): Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)
02-12 12:21:13.662: W/dalvikvm(9129): Link of class 'Lcom/mopub/network/AdRequest;' failed
02-12 12:21:13.672: E/AndroidRuntime(9129): Caused by: java.lang.NoClassDefFoundError: com.mopub.mobileads.AdViewController$1
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.AdViewController.<init>(AdViewController.java:107)
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.factories.AdViewControllerFactory.internalCreate(AdViewControllerFactory.java:21)
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.factories.AdViewControllerFactory.create(AdViewControllerFactory.java:17)
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:82)
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:56)
02-12 12:21:13.672: E/AndroidRuntime(9129): 	at com.mopub.mobileads.MoPubUnityPlugin$1.run(MoPubUnityPlugin.java:43)
02-12 12:21:13.682: E/EmbeddedLogger(441): App crashed! Process: com.Debug.mopubtest
02-12 12:21:13.682: E/EmbeddedLogger(441): App crashed! Package: com.Debug.mopubtest v1 (1.0)
02-12 12:21:13.682: E/EmbeddedLogger(441): Application Label: MoPubTest
02-12 12:21:13.682: W/ActivityManager(441):   Force finishing activity com.Debug.mopubtest/com.unity3d.player.UnityPlayerNativeActivity
02-12 12:21:14.222: W/ActivityManager(441): Activity pause timeout for ActivityRecord{42aec338 com.Debug.mopubtest/com.unity3d.player.UnityPlayerNativeActivity}
02-12 12:21:24.222: W/ActivityManager(441): Activity idle timeout for ActivityRecord{42c7ffc0 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity}
02-12 12:21:43.902: W/ActivityManager(441): Activity pause timeout for ActivityRecord{42c7ffc0 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity}
02-12 12:21:47.352: W/ActivityManager(441): Activity pause timeout for ActivityRecord{42c7ffc0 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity}
02-12 12:21:49.472: I/ActivityManager(441): Process com.Debug.mopubtest (pid 9129) has died.
02-12 12:21:49.472: I/WindowState(441): WIN DEATH: Window{42c209a8 com.Debug.mopubtest/com.unity3d.player.UnityPlayerNativeActivity paused=false}
02-12 12:21:49.472: W/WindowManager(441): Force-removing child win Window{421dc798 SurfaceView paused=false} from container Window{42c209a8 com.Debug.mopubtest/com.unity3d.player.UnityPlayerNativeActivity paused=false}
02-12 12:21:49.472: W/ActivityManager(441): Force removing ActivityRecord{42c7ffc0 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity}: app died, no saved state
02-12 12:21:49.482: I/WindowState(441): WIN DEATH: Window{42a87808 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity paused=false}
02-12 12:21:49.502: I/WindowManager(441): WINDOW DIED Window{42a87808 com.Debug.mopubtest/com.unity3d.player.UnityPlayerProxyActivity paused=false}
02-12 12:21:53.932: W/ActivityManager(441): Activity destroy timeout for ActivityRecord{42aec338 com.Debug.mopubtest/com.unity3d.player.UnityPlayerNativeActivity}

**Comment by maxim-sheronov** [comment]
Hi.
I faced with same issue. And I found solution.
You can see reason at row "Unable to resolve superclass of Lcom/mopub/network/AdRequest; (982)"
Because parent is com.mopub.volley.Request - in anothe library (can see in gradle.build) com.mopub.volley:mopub-volley:1.1.0
So you need add jar of this library to your project.
Hope it is help.
